entity_activity_tracker.activity_processor.settings.credit_group_comment_creation:
  type: entity_activity_tracker.activity_processor.settings_base
  mapping:
    credit_group:
      type: integer

entity_activity_tracker.activity_processor.settings.credit_group_content_creation:
  type: entity_activity_tracker.activity_processor.settings_base
  mapping:
    credit_group:
      type: integer

entity_activity_tracker.activity_processor.settings.credit_group_content_commented_entity:
  type: entity_activity_tracker.activity_processor.settings_base
  mapping:
    credit_group:
      type: integer

entity_activity_tracker.activity_processor.settings.credit_group_membership_comment_creation:
  type: entity_activity_tracker.activity_processor.settings_base
  mapping:
    credit_group:
      type: integer
